// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfMpvmxUGld94uyOZhSTLHMkeDiKh6MA8',
    appId: '1:598612936357:web:b3f50feb7581ca58c72f4c',
    messagingSenderId: '598612936357',
    projectId: 'assignment-a2c37',
    authDomain: 'assignment-a2c37.firebaseapp.com',
    storageBucket: 'assignment-a2c37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsihA6eXLTvF0pmaO7HthGUqZvcWdXato',
    appId: '1:598612936357:android:c32fabcba790deabc72f4c',
    messagingSenderId: '598612936357',
    projectId: 'assignment-a2c37',
    storageBucket: 'assignment-a2c37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQVZ1GElufnB0cznVb-SAFCzl_yTG4Rs',
    appId: '1:598612936357:ios:c146c702651b4a2ac72f4c',
    messagingSenderId: '598612936357',
    projectId: 'assignment-a2c37',
    storageBucket: 'assignment-a2c37.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfQVZ1GElufnB0cznVb-SAFCzl_yTG4Rs',
    appId: '1:598612936357:ios:b5fe8b1ba8b21ec0c72f4c',
    messagingSenderId: '598612936357',
    projectId: 'assignment-a2c37',
    storageBucket: 'assignment-a2c37.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
